# Generated by Django 3.0.8 on 2020-07-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sautcom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('min_limit', models.FloatField()),
                ('max_limit', models.FloatField()),
                ('averaging', models.IntegerField()),
            ],
        ),
    ]
