# Generated by Django 2.1.5 on 2020-08-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sensor', models.CharField(max_length=20, unique=True)),
                ('type_of_technological_section', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('min_limit', models.FloatField()),
                ('max_limit', models.FloatField()),
                ('averaging', models.IntegerField()),
                ('date_begin', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
            ],
        ),
    ]
