# Generated by Django 3.0.8 on 2020-07-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_limitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Limitations',
            new_name='Limitation',
        ),
    ]
