# Generated by Django 3.0.8 on 2020-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_limitations', '0002_auto_20200730_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='id_sautcom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
