# Generated by Django 3.0.8 on 2020-08-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_limitations', '0003_auto_20200730_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='type_of_technological_section',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
